language: go
go:
  - "1.14"
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - go get -t ./...
script:
  - go test -coverprofile=xo.coverprofile
  - $HOME/gopath/bin/goveralls -coverprofile=xo.coverprofile -service=travis-ci
matrix:
  allow_failures:
    - go: tip
